const SUPABASE_URL = "https://ndrqtzauswhmrovolroj.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kcnF0emF1c3dobXJvdm9scm9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkwNTU5NzAsImV4cCI6MjEwNDYzMTk3MH0.pwgmihDrK2cvIJOyx4OdXuLx4a9jtD_sQUvYkZFy3f4";

